name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push the package.json commit back to github
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Tests
        run: npm run test

      - name: Configure Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update package.json version to match Release Tag
        run: |
          RAW_VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${RAW_VERSION#v}
          npm version $VERSION --no-git-tag-version
          
          # Commit and push the updated package.json back to the repo
          git add package.json package-lock.json
          git commit -m "chore: bump version to $VERSION [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Build Library
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
